/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param carrelloId 
 * @param prodottoId 
 * @param quantita 
 */


data class CarrelloProdottiDto (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "carrelloId")
    val carrelloId: kotlin.Long? = null,

    @Json(name = "prodottoId")
    val prodottoId: kotlin.Long? = null,

    @Json(name = "quantita")
    val quantita: kotlin.Int? = null

) {


}

