/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id
 * @param nome
 * @param immagine
 */


data class CategoriaDto (

    @Json(name = "id")
    val id: Long? = null,

    @Json(name = "nome")
    val nome: String? = null,

    @Json(name = "immagine")
    val immagine: String? = null

)

