/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param via
 * @param numeroCivico
 * @param citta
 */


data class Indirizzo (

    @Json(name = "via")
    val via: String? = null,

    @Json(name = "numeroCivico")
    val numeroCivico: Int? = null,

    @Json(name = "citta")
    val citta: String? = null

)

