/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.ea.lemu_frontend.models

import org.openapitools.client.models.Ordine
import org.openapitools.client.models.Prodotto

import com.squareup.moshi.Json

/**
 *
 *
 * @param id
 * @param ordine
 * @param prodotto
 * @param quantita
 */


data class OrdineProdotto (

    @Json(name = "id")
    val id: Long? = null,

    @Json(name = "ordine")
    val ordine: Ordine? = null,

    @Json(name = "prodotto")
    val prodotto: Prodotto? = null,

    @Json(name = "quantita")
    val quantita: Int? = null

)

