/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrdineProdottoDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param indirizzo 
 * @param idutente 
 * @param dataAcquisto 
 * @param prezzoTotaleOrdine 
 * @param ordineProdotti 
 */


data class OrdineDto (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "indirizzo")
    val indirizzo: kotlin.String? = null,

    @Json(name = "idutente")
    val idutente: kotlin.Long? = null,

    @Json(name = "dataAcquisto")
    val dataAcquisto: java.time.LocalDate? = null,

    @Json(name = "prezzoTotaleOrdine")
    val prezzoTotaleOrdine: kotlin.Double? = null,

    @Json(name = "ordineProdotti")
    var ordineProdotti: kotlin.collections.List<OrdineProdottoDto>? = null

) {


}

