/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PageableObject
import org.openapitools.client.models.RecensioneDto
import org.openapitools.client.models.SortObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param totalElements 
 * @param totalPages 
 * @param propertySize 
 * @param content 
 * @param number 
 * @param sort 
 * @param first 
 * @param last 
 * @param numberOfElements 
 * @param pageable 
 * @param empty 
 */


data class PageRecensioneDto (

    @Json(name = "totalElements")
    val totalElements: kotlin.Long? = null,

    @Json(name = "totalPages")
    val totalPages: kotlin.Int? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "content")
    val content: kotlin.collections.List<RecensioneDto>? = null,

    @Json(name = "number")
    val number: kotlin.Int? = null,

    @Json(name = "sort")
    val sort: SortObject? = null,

    @Json(name = "first")
    val first: kotlin.Boolean? = null,

    @Json(name = "last")
    val last: kotlin.Boolean? = null,

    @Json(name = "numberOfElements")
    val numberOfElements: kotlin.Int? = null,

    @Json(name = "pageable")
    val pageable: PageableObject? = null,

    @Json(name = "empty")
    val empty: kotlin.Boolean? = null

) {


}

