/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SortObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param offset 
 * @param sort 
 * @param pageSize 
 * @param pageNumber 
 * @param paged 
 * @param unpaged 
 */


data class PageableObject (

    @Json(name = "offset")
    val offset: kotlin.Long? = null,

    @Json(name = "sort")
    val sort: SortObject? = null,

    @Json(name = "pageSize")
    val pageSize: kotlin.Int? = null,

    @Json(name = "pageNumber")
    val pageNumber: kotlin.Int? = null,

    @Json(name = "paged")
    val paged: kotlin.Boolean? = null,

    @Json(name = "unpaged")
    val unpaged: kotlin.Boolean? = null

) {


}

