/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Recensione
import org.openapitools.client.models.Utente

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param nome 
 * @param descrizione 
 * @param prezzo 
 * @param venduti 
 * @param categoria 
 * @param immagineProdotto 
 * @param valutazione 
 * @param numeroRecensioni 
 * @param recensione 
 * @param utente 
 * @param disponibilita 
 */


data class ProdottoDto (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "nome")
    val nome: kotlin.String? = null,

    @Json(name = "descrizione")
    val descrizione: kotlin.String? = null,

    @Json(name = "prezzo")
    val prezzo: kotlin.Float? = null,

    @Json(name = "venduti")
    val venduti: kotlin.Int? = null,

    @Json(name = "categoria")
    val categoria: kotlin.String? = null,

    @Json(name = "immagineProdotto")
    val immagineProdotto: kotlin.String? = null,

    @Json(name = "valutazione")
    val valutazione: kotlin.Double? = null,

    @Json(name = "numeroRecensioni")
    val numeroRecensioni: kotlin.Int? = null,

    @Json(name = "recensione")
    val recensione: kotlin.collections.List<Recensione>? = null,

    @Json(name = "utente")
    val utente: Utente? = null,

    @Json(name = "disponibilita")
    val disponibilita: kotlin.Int? = null

)

