/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Recensione
import org.openapitools.client.models.Utente

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id
 * @param nome
 * @param descrizione
 * @param prezzo
 * @param venduti
 * @param categoria
 * @param immagineProdotto
 * @param recensione
 * @param utente
 * @param disponibilita
 */


data class Prodotto (

    @Json(name = "id")
    val id: Long? = null,

    @Json(name = "nome")
    val nome: String? = null,

    @Json(name = "descrizione")
    val descrizione: String? = null,

    @Json(name = "prezzo")
    val prezzo: Float? = null,

    @Json(name = "venduti")
    val venduti: Int? = null,

    @Json(name = "categoria")
    val categoria: String? = null,

    @Json(name = "immagineProdotto")
    val immagineProdotto: String? = null,

    @Json(name = "recensione")
    val recensione: List<Recensione>? = null,

    @Json(name = "utente")
    val utente: Utente? = null,

    @Json(name = "disponibilita")
    val disponibilita: Boolean? = null

)

