/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param nome 
 * @param descrizione 
 * @param prezzo 
 * @param venduti 
 * @param categoria 
 * @param idrecensioni 
 * @param idutente 
 * @param disponibilita 
 * @param immagineProdotto 
 */


data class ProdottoDto(

    @Json(name = "id")
    val id: Long? = null,

    @Json(name = "nome")
    val nome: String? = null,

    @Json(name = "descrizione")
    val descrizione: String? = null,

    @Json(name = "prezzo")
    val prezzo: String = null.toString(),

    @Json(name = "venduti")
    val venduti: Int? = null,

    @Json(name = "categoria")
    val categoria: String? = null,

    @Json(name = "idrecensioni")
    val idrecensioni: List<Long>? = null,

    @Json(name = "idutente")
    val idutente: Long? = null,

    @Json(name = "disponibilita")
    val disponibilita: Int? = null,

    @Json(name = "immagineProdotto")
    val immagineProdotto: String? = null

) {


}

