/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Prodotto
import org.openapitools.client.models.Utente

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id
 * @param rating
 * @param commento
 * @param prodotto
 * @param autore
 */


data class Recensione (

    @Json(name = "id")
    val id: Long? = null,

    @Json(name = "rating")
    val rating: Float? = null,

    @Json(name = "commento")
    val commento: String? = null,

    @Json(name = "prodotto")
    val prodotto: Prodotto? = null,

    @Json(name = "autore")
    val autore: Utente? = null

)

