/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param direction 
 * @param nullHandling 
 * @param ascending 
 * @param `property` 
 * @param ignoreCase 
 */


data class SortObject (

    @Json(name = "direction")
    val direction: kotlin.String? = null,

    @Json(name = "nullHandling")
    val nullHandling: kotlin.String? = null,

    @Json(name = "ascending")
    val ascending: kotlin.Boolean? = null,

    @Json(name = "property")
    val `property`: kotlin.String? = null,

    @Json(name = "ignoreCase")
    val ignoreCase: kotlin.Boolean? = null

) {


}

