/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Carrello
import org.openapitools.client.models.Credenziali
import org.openapitools.client.models.Indirizzo
import org.openapitools.client.models.Ordine
import org.openapitools.client.models.Recensione
import org.openapitools.client.models.Wishlist

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id
 * @param nome
 * @param cognome
 * @param isAdmin
 * @param bannato
 * @param immagineProfilo
 * @param indirizzo
 * @param credenziali
 * @param carrello
 * @param wishlist
 * @param recensione
 * @param ordini
 */


data class Utente (

    @Json(name = "id")
    val id: Long? = null,

    @Json(name = "nome")
    val nome: String? = null,

    @Json(name = "cognome")
    val cognome: String? = null,

    @Json(name = "isAdmin")
    val isAdmin: Boolean? = null,

    @Json(name = "bannato")
    val bannato: Boolean? = null,

    @Json(name = "immagineProfilo")
    val immagineProfilo: String? = null,

    @Json(name = "indirizzo")
    val indirizzo: Indirizzo? = null,

    @Json(name = "credenziali")
    val credenziali: Credenziali? = null,

    @Json(name = "carrello")
    val carrello: Carrello? = null,

    @Json(name = "wishlist")
    val wishlist: Wishlist? = null,

    @Json(name = "recensione")
    val recensione: List<Recensione>? = null,

    @Json(name = "ordini")
    val ordini: List<Ordine>? = null

)

