/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param credenzialiPassword 
 * @param credenzialiEmail 
 */


data class UtenteLoginDto (

    @Json(name = "credenzialiPassword")
    val credenzialiPassword: kotlin.String,

    @Json(name = "credenzialiEmail")
    val credenzialiEmail: kotlin.String? = null

)

