/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Prodotto
import org.openapitools.client.models.Wishlist

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param wishlist 
 * @param prodotto 
 */


data class WishlistProdotti (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "wishlist")
    val wishlist: Wishlist? = null,

    @Json(name = "prodotto")
    val prodotto: Prodotto? = null

)

